version: "3.4"

services:
#  mailcatcher:
#    image: schickling/mailcatcher
#    ports:
#      - "1080:1080"
#      - "1025:1025"
  web:
    
    build: ./
    image: tsvetanka/it_taskportal-1
   
    
    command: gunicorn IT_TaskPortal.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - ./staticfiles:/tmp/IT_TaskPortal/staticfiles
      - ./mediafiles:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.prod
    depends_on:
      - postgres
#      - mailcatcher
    postgres:
 
    restart: always
    ports:
      - "5432:5432"
    environment:
      
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: it_database
      PGDATA: /var/lib/postgresql/data/pgdata
      
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./mediafiles:/home/app/web/mediafiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

    depends_on:
      - web
